### ISSUE TITLE
Measure automated test run times

### ISSUE THREAD

**Issue by njitbra** [JesseHilario/mywebclass-simulation#29]
Tasks:
- Create a script to record start and end times for each test.
- Run script and collect timing data for each test.
- Analyze the data _(to identify any tests that are taking longer than expected or that seem to be consistently slow)_.
- Implement changes _(to optimize the identified slow tests)_.
- Re-run test and collect timing data again _(to measure the impact of the optimizations)_.
- Analyze the new data _(to determine if the optimizations had the intended effect)_.
- Share the results with the team.

**Comment by JesseHilario** [comment]
added to team productivity log
